### ISSUE TITLE
Tokens corresponding to Amazon/Azure profiles in notebook names don't work when another notebook is run within source notebook. 

### ISSUE THREAD

**Issue by dkucar** [databricks-edu/build-tooling#96]
I would like to exclude **Kinesis-WIki-Stream-Producer** from the Azure build.

To accomplish this:

In the source (file browser), the notebook is called
**am-Kinesis-Wiki-Stream-Producer.py**

in the build.yaml file, I have
```  
- src: Self-Paced/Structured-Streaming/Includes/Kinesis-Wiki-Stream-Producer.py
    dest: "$target_lang/$notebook_type/Includes/$basename.$target_extension"
    **only_in_profile: amazon**
    master:
      footer:
        enabled: false
      heading:
        enabled: false
```

However, in the source file I run the notebook as I would in the build, which does not work because it is actually called **am-Kinesis-Wiki-Stream-Producer.py**

In a notebook, I run
%run "./Includes/Kinesis-Wiki-Stream-Producer"

-----
Example notebook:
https://trainers.cloud.databricks.com/#notebook/15025696
